Dockerisation update with Dockerfile and requirements.txt
eastgenomics/run_dx_checker pull request #4
Opened 2023-02-22 09:24 UTC by PolarisAstrum

Added requirements.txt containing python package requirements for pip to install before running run_dx_checker.
Added Dockerfile to allow run_dx_checker to be run using docker.

2023-02-22 09:34 UTC, JasonLing95 commented on Dockerfile
> +COPY run_dx_checker.py run_dx_checker.py /
duplication

2023-02-22 09:35 UTC, JasonLing95 reviewed
how are you reading the environment variables when the docker container is ran

2023-02-22 09:40 UTC, PolarisAstrum commented on Dockerfile
> +COPY run_dx_checker.py run_dx_checker.py /
What is there a duplication of?

2023-02-22 10:01 UTC, PolarisAstrum commented
I didn't make any changes to reading in the environment variables. This takes place in the run_dx_checker.py script, which reads the environment variables from the config.py file and dnanexus_token.py file.

2023-02-22 10:19 UTC, JasonLing95 commented
could you add a way for docker to read those env variables from its container environment `os.environ['AUTH_TOKEN']` so that when we need to change the env in the future, we could just change it on a config file. 

The command will be `docker run --env-file <the config file path> dx-checker`. And add an [example config](https://github.com/eastgenomics/automated-archiving/blob/main/env.example) too

2023-02-22 10:35 UTC, JasonLing95 commented
Yup, just in case the API token might expire or we might need to change project-id or workflow-id. It is something you need to add to the python script (run_dx_checker.py) (here's an [example](https://github.com/eastgenomics/automated-archiving/blob/main/main.py))

2023-02-22 10:43 UTC, PolarisAstrum commented
Ah, I think this is already a feature. The projectID, workflowID, and AUTH_TOKEN are already specified in the config file. Currently the AUTH_TOKEN is specified in a separate config file named "dnanexus_token.py", while the project and workflow IDs are specified in "config.py". I could move AUTH_TOKEN to "config.py" and remove "dnanexus_token.py" I suppose.

2023-02-22 16:20 UTC, JasonLing95 requested changes

2023-02-22 16:20 UTC, JasonLing95 commented on Dockerfile
> +COPY run_dx_checker.py run_dx_checker.py /
shouldn't this just be `COPY run_dx_checker.py /`

2023-02-22 16:20 UTC, JasonLing95 commented on run_dx_checker.py
> +            'project': os.environ['genomebwaindex_targz_projectID'],
`import os`

2023-02-22 16:20 UTC, JasonLing95 commented on config.txt
> +genomebwaindex_targz_projectID=project-F3zxk7Q4F30Xp8fG69K1Vppj
Capitalize all the env `GENOMEBWAINDEX_TARGZ_PROJECTID`

2023-02-22 16:20 UTC, JasonLing95 commented on run_dx_checker.py
> +projectID = os.environ['projectID']
Uppercase `projectID` and all env below

2023-02-23 09:16 UTC, PolarisAstrum commented on Dockerfile
> +COPY run_dx_checker.py run_dx_checker.py /
Yep, the command is fixed now

2023-02-23 09:16 UTC, PolarisAstrum commented on run_dx_checker.py
> +            'project': os.environ['genomebwaindex_targz_projectID'],
Added

2023-02-23 09:16 UTC, PolarisAstrum commented on config.txt
> +genomebwaindex_targz_projectID=project-F3zxk7Q4F30Xp8fG69K1Vppj
All env vars are capitalised now

2023-02-23 09:17 UTC, PolarisAstrum commented on run_dx_checker.py
> +projectID = os.environ['projectID']
All env names match in the config.txt and run_dx_checker.py now

2023-02-23 09:31 UTC, JasonLing95 commented
@PolarisAstrum Could you add a `print()` statement at the end of `main()` function so that we know the script completed running

2023-02-23 09:40 UTC, PolarisAstrum commented
The print statement has been added

2023-02-23 09:55 UTC, merged